"""
Find the Difference

Given two strings where the second is generated by shuffling the first and
adding one extra letter, find the added letter using XOR.

Reference: https://en.wikipedia.org/wiki/Exclusive_or

Complexity:
    Time:  O(n) where n is the length of the longer string
    Space: O(1)
"""

from __future__ import annotations


def find_difference(original: str, shuffled: str) -> str:
    """Find the single character added to a shuffled copy of a string.

    Uses XOR on all character code points; paired characters cancel out,
    leaving only the extra character.

    Args:
        original: The original string.
        shuffled: The shuffled string with one extra character.

    Returns:
        The single character that was added.

    Examples:
        >>> find_difference("abcd", "abecd")
        'e'
    """
    xor_result = 0
    for character in original + shuffled:
        xor_result ^= ord(character)
    return chr(xor_result)
